apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: sample-2
spec:
  flows:
  - route:
      from:
        parameters:
          period: 30000
        steps:
        - setBody:
            simple: Hello Camel from {{my.env}} - {{my.property}}
        - log: ${body}
        uri: timer:yaml
  replicas: 1
  traits:
    camel:
      properties:
      - my.property=Camel K - sample 2 in action!
      runtimeProvider: plain-quarkus
      runtimeVersion: 3.20.4
    container:
      image: 10.104.35.69/dev/camel-k-kit-d62b3llas3uc73d2brb0@sha256:417371627f78b93493b86f7eceeb5c3e219a60392582453a19b48452949c2a2e
      limitCPU: 250m
      limitMemory: 256Mi
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    mount:
      configs:
      - configmap:my-cm
status: {}
