apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: sample-1
spec:
  flows:
  - route:
      from:
        parameters:
          period: 30000
        steps:
        - setBody:
            simple: Hello Camel from {{my.env}} - {{my.property}}
        - log: ${body}
        uri: timer:yaml
  replicas: 1
  traits:
    camel:
      properties:
      - my.property=Camel K - sample 1 in action!
      runtimeProvider: plain-quarkus
      runtimeVersion: 3.27.2
    container:
      image: 10.104.35.69/dev/camel-k-kit-d62blllas3uc73d2brd0@sha256:25299794ec8c28f63dcb88a1f92df4d816644801db5c6ef592360f6a8042f635
      limitCPU: 250m
      limitMemory: 256Mi
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
    mount:
      configs:
      - configmap:my-cm
status: {}
