apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: sample-1
spec:
  flows:
  - route:
      from:
        parameters:
          period: "1000"
        steps:
        - setBody:
            simple: Hello Camel from ${routeId}
        - log: ${body}
        uri: timer:yaml
  replicas: 1
  traits:
    builder:
      properties:
      - a=2
    camel:
      runtimeVersion: 3.15.3
    container:
      image: 10.110.254.179/dev/camel-k-kit-d5p6cdl3574c73dtp3sg@sha256:18fa92e15d16002358c0e7083b13babef8d848986a7ee952b76ac4b167996d4e
    jvm:
      classpath: dependencies/*:dependencies/app/*:dependencies/lib/boot/*:dependencies/lib/main/*:dependencies/quarkus/*
status: {}
